### ISSUE TITLE
the webservice should handle old and new HMDB identifiers

### ISSUE THREAD

**Issue by egonw** [bridgedb/bridgedb-webservice#1]
That is, the following two links should return the same attributes:

- https://webservice.bridgedb.org/Human/attributes/Ch/HMDB0000108
- https://webservice.bridgedb.org/Human/attributes/Ch/HMDB00108

(right now, one does not return anything at all)

The solution is in the webservice Java code check which one it uses, and change it to the style that does return attributes. Search for HMDB00 in the BridgeDb code to see how we did this elsewhere: https://github.com/bridgedb/create-bridgedb-metabolites/commit/aef2f38e0bcbfb8e4c4d4c38f2c59cba6c4e3752

**Comment by hbasaric** [comment]
Fixed HMDB new identifiers bug: https://github.com/bridgedb/bridgedb-webservice/pull/5

**Comment by egonw** [comment]
Fixed in https://github.com/bridgedb/BridgeDbWebservice
